using System.Net.Http;
using System.Text.RegularExpressions;
using FydelisTech_Attack.Core.Models;
using System.Collections;

namespace FydelisTech_Attack.Core.Services;

public class WafDetectionService
{
    private readonly HttpClient _httpClient;

    public WafDetectionService(int timeoutMs = 10000)
    {
        _httpClient = new HttpClient
        {
            Timeout = TimeSpan.FromMilliseconds(timeoutMs)
        };
        _httpClient.DefaultRequestHeaders.Add("User-Agent",
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36");
    }

    public async Task<WafResult> DetectAsync(string domain, CancellationToken ct = default)
    {
        var result = new WafResult();
        var testUrls = new[]
        {
            $"https://{domain}/?id=1' OR '1'='1",
            $"https://{domain}/?id=<script>alert(1)</script>",
            $"https://{domain}/?id=../../../etc/passwd",
            $"https://{domain}/?id=1 UNION SELECT * FROM users",
            $"https://{domain}/"
        };

        var wafSignatures = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["Cloudflare"] = "cloudflare|__cfduid|cf-ray|cf-cache-status|server: cloudflare",
            ["AWS WAF"] = "x-amzn-requestid|x-amz-cf-id|aws waf|awselb",
            ["ModSecurity"] = "mod_security|modsecurity|noby|this error was generated by",
            ["Akamai"] = "akamai|akamaighost|x-akamai|akamaipixel",
            ["F5 BIG-IP"] = "bigip|f5|x-connection-info|tscbcookie",
            ["Imperva/Incapsula"] = "incapsula|x-iinfo|_incapsula_|visid_incap",
            ["Sucuri"] = "sucuri|x-sucuri-id|sucuri/cloudproxy|cloudproxy",
            ["Wordfence"] = "wordfence|generated by wordfence",
            ["Barracuda"] = "barracuda|barracoon|x-bb-ip",
            ["Citrix Netscaler"] = "netscaler|ns_af|citrix|appfw",
            ["Fortinet FortiWeb"] = "fortiw eb|fortinet|x-requested-with: fortiw eb",
            ["Radware"] = "radware|appwall|x-slot|x-cap",
            ["KnownUnknown"] = "tmg|threat management gateway|microsoft tm g"
        };

        foreach (var url in testUrls)
        {
            if (ct.IsCancellationRequested) break;

            try
            {
                var request = new HttpRequestMessage(HttpMethod.Get, url);
                var response = await _httpClient.SendAsync(request, ct);
                var body = await response.Content.ReadAsStringAsync(ct);
                var lowerBody = body.ToLower();
                var headersStr = string.Join(" ", response.Headers.Select(h => $"{h.Key}: {string.Join(", ", h.Value)}")).ToLower();

                foreach (var waf in wafSignatures)
                {
                    if (Regex.IsMatch(headersStr, waf.Value, RegexOptions.IgnoreCase) ||
                        Regex.IsMatch(lowerBody, waf.Value, RegexOptions.IgnoreCase))
                    {
                        result.HasWaf = true;
                        result.WafName = waf.Key.Split(' ')[0];
                        result.WafVendor = waf.Key;
                        result.Confidence = DetectionConfidence.High;
                        result.DetectedSignatures.Add($"Assinatura '{waf.Key}' encontrada em {url}");
                        break;
                    }
                }

                var statusCode = (int)response.StatusCode;
                if (statusCode is 406 or 501 or 999 or 429)
                {
                    result.HasWaf = true;
                    result.DetectedSignatures.Add($"HTTP {statusCode} em {url} (possível bloqueio WAF)");
                    if (result.Confidence < DetectionConfidence.Medium)
                        result.Confidence = DetectionConfidence.Medium;
                }
            }
            catch { }
        }

        result.DetectedSignatures = result.DetectedSignatures.Distinct().ToList();
        if (result.DetectedSignatures.Count == 0)
            result.Confidence = DetectionConfidence.Low;

        return result;
    }
}